# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About', folder: '_posts', file: 'about.html'}
- {name: 'Blog', folder: '_posts', file: 'blog.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/latlan1'}
- {icon: 'envelope', link: 'mailto:latlan@seas.upenn.edu'}
- {icon: 'github', link: 'https://latlan1.github.io'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy...'

#post_date_prefix: 'Written on'
